# Generated by Django 5.2.14 on 2026-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_draft_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
