# Generated by Django 5.2.14 on 2026-05-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Logística de producto',
                'verbose_name_plural': 'Opciones de logística de producto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modalidad económica',
                'verbose_name_plural': 'Modalidades económicas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='QuienGraba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quién graba',
                'verbose_name_plural': 'Opciones de quién graba',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='QuienPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quién publica',
                'verbose_name_plural': 'Opciones de quién publica',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='QuienRevisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quién revisa',
                'verbose_name_plural': 'Opciones de quién revisa',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecogidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recogida de producto',
                'verbose_name_plural': 'Opciones de recogida de producto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='WinStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado Win',
                'verbose_name_plural': 'Estados Win',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='project',
            name='devolucion_producto',
            field=models.BooleanField(default=False, verbose_name='Devolución de producto'),
        ),
        migrations.AddField(
            model_name='project',
            name='fecha_limite_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de entrega'),
        ),
        migrations.AddField(
            model_name='project',
            name='fecha_llegada_producto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de llegada del producto'),
        ),
        migrations.AddField(
            model_name='project',
            name='semaforo_proyecto',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Semáforo proyecto'),
        ),
        migrations.AddField(
            model_name='projectcontentmaker',
            name='is_suplente',
            field=models.BooleanField(default=False, help_text='Si es suplente, recibe la solicitud automáticamente si una Principal rechaza.'),
        ),
        migrations.AddField(
            model_name='projectcontentmaker',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de aceptación/rechazo.', null=True),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Brief / Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin del proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fecha_servicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del servicio'),
        ),
        migrations.AddField(
            model_name='project',
            name='logistica_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.logisticaproducto', verbose_name='Logística producto'),
        ),
        migrations.AddField(
            model_name='project',
            name='modalidad_economica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.modalidadeconomica', verbose_name='Modalidad económica'),
        ),
        migrations.AddField(
            model_name='project',
            name='quien_graba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.quiengraba', verbose_name='Quién graba'),
        ),
        migrations.AddField(
            model_name='project',
            name='quien_publica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.quienpublica', verbose_name='Quién publica'),
        ),
        migrations.AddField(
            model_name='project',
            name='quien_revisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.quienrevisa', verbose_name='Quién revisa'),
        ),
        migrations.AddField(
            model_name='project',
            name='recogida_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.recogidaproducto', verbose_name='Recogida del producto'),
        ),
        migrations.AddField(
            model_name='project',
            name='win_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.winstatus', verbose_name='Win?'),
        ),
    ]
