# Generated by Django 5.2.13 on 2026-05-25 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_makers', '0008_tallaje_category_model'),
        ('projects', '0009_seed_operational_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='retrasado',
            field=models.BooleanField(default=False, help_text='Flag paralelo: se activa si llega la fecha límite sin entregable.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_cm_select', 'Seleccionar Content Maker'), ('project_cm_request', 'Solicitud a Content Maker'), ('project_cm_accepted', 'Content Maker aceptó'), ('project_cm_rejected', 'Content Maker rechazó'), ('briefing_submitted', 'Briefing enviado'), ('deadline_reminder', 'Recordatorio pre-entrega'), ('deadline_overdue', 'Entrega vencida'), ('delivery_uploaded', 'Entregable subido'), ('revision_requested', 'Revisión solicitada'), ('delivery_approved', 'Entregable aprobado'), ('cm_promoted', 'Suplente promovida'), ('account_created', 'Cuenta creada'), ('status_changed', 'Estado del proyecto cambiado')], max_length=30),
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregables/')),
                ('descripcion', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('revision', 'Requiere cambios'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('revision_round', models.PositiveSmallIntegerField(default=1, help_text='Ronda de revisión actual (máximo 2).')),
                ('revision_notes', models.TextField(blank=True, help_text='Notas de la PM para la revisión.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Fecha de publicación del contenido.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='content_makers.contentmakerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False, help_text='True si el cambio fue forzado manualmente por Admin/Empleada.')),
                ('reason', models.TextField(blank=True, help_text='Motivo obligatorio cuando es override manual.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectstatus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='projects.project')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectstatus')),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Cambios de estado',
                'ordering': ['-timestamp'],
            },
        ),
    ]
