# Generated by Django 5.2.14 on 2026-05-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_retrasado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='link_referencia',
        ),
        migrations.CreateModel(
            name='BriefingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.briefing')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BriefingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='briefings/photos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.briefing')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
