# Generated by Django 5.2.13 on 2026-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_briefing_links_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='descuento_activo',
            field=models.BooleanField(default=False, verbose_name='Aplicar descuento'),
        ),
        migrations.AddField(
            model_name='project',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fee (€/contenido)'),
        ),
        migrations.AddField(
            model_name='project',
            name='gifting',
            field=models.BooleanField(default=False, help_text='Si está activo, Stimada invita al contenido y el importe final es 0 €.', verbose_name='Gifting'),
        ),
        migrations.AddField(
            model_name='project',
            name='num_contenidos',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de contenidos'),
        ),
        migrations.AddField(
            model_name='project',
            name='num_perfiles',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de perfiles'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='disponible_en_creacion',
            field=models.BooleanField(default=False, help_text='Si está activo, este estado puede seleccionarse como estado inicial al crear un proyecto.', verbose_name='Disponible al crear'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='requiere_perfiles',
            field=models.BooleanField(default=False, help_text='Si está activo, al seleccionar este tipo de servicio se mostrarán las secciones de Red Social y Formato.', verbose_name='Requiere red social y formato'),
        ),
        migrations.AddField(
            model_name='project',
            name='formatos',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.formato', verbose_name='Formatos'),
        ),
        migrations.AddField(
            model_name='project',
            name='redes_sociales',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.redsocial', verbose_name='Redes sociales'),
        ),
    ]
