# Generated by Django 5.2.13 on 2026-05-25 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Copia del email del usuario en el momento del cambio (inmutable).', max_length=254)),
                ('entity_type', models.CharField(choices=[('content_maker', 'Content Maker'), ('client', 'Cliente'), ('brand', 'Marca'), ('project', 'Proyecto'), ('user', 'Usuario')], max_length=30)),
                ('entity_id', models.PositiveIntegerField()),
                ('entity_repr', models.CharField(blank=True, help_text='Representación legible de la entidad en el momento del cambio.', max_length=300)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Motivo del cambio (obligatorio en override manual de estado de proyecto).')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('override', 'Override manual')], default='update', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['field_name'], name='audit_audit_field_n_5f69a9_idx')],
            },
        ),
    ]
