# Generated by Django 5.2.13 on 2026-04-29 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_user_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='es_agencia',
            field=models.BooleanField(default=False, help_text='Si es agencia, puede tener múltiples marcas asociadas.'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
                'unique_together': {('client', 'nombre')},
            },
        ),
    ]
