# Generated by Django 5.2.14 on 2026-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientprofile_es_agencia_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='cliente_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
