# Generated by Django 5.2.13 on 2026-05-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientprofile_favorite_cms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10),
        ),
        migrations.AddField(
            model_name='brand',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='tipo_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas', to='clients.clienttype', verbose_name='Tipo de marca'),
        ),
        migrations.AddField(
            model_name='brand',
            name='web_instagram',
            field=models.URLField(blank=True, max_length=300, verbose_name='Web / Instagram'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='notas_internas',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='semaforo_cliente',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Semáforo cliente'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='web_instagram',
            field=models.URLField(blank=True, max_length=300, verbose_name='Web / Instagram'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Marca'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='nombre_cliente',
            field=models.CharField(max_length=200, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='nombre_facturacion',
            field=models.CharField(max_length=200, verbose_name='Razón social'),
        ),
    ]
