# Generated by Django 5.2.14 on 2026-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_brand_full_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='brand',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='brand',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
    ]
