# Generated by Django 5.2.13 on 2026-04-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_makers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMakerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de Content Maker',
                'verbose_name_plural': 'Estados de Content Maker',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContentMakerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Content Maker',
                'verbose_name_plural': 'Tipos de Content Maker',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='contentmakerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
