# Generated by Django 5.2.14 on 2026-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_makers', '0004_contentmakerprofile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmakerprofile',
            name='stimada_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
